[project]
name = "swissquote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.3.6",
    "matplotlib>=3.10.1",
    "tabulate>=0.9.0",
    "yfinance>=0.2.55",
]
